fix error occuring when running >status in calls
TypeError: Cannot read property 'then' of undefined
    at module.exports (/root/dtel/Events/message.js:73:38)

because its not returning a promise